<a href="https://colab.research.google.com/github/mewan12/mewan12/blob/main/ad_sales_predicts_on_exsisting_customer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Day 3 Ad. Sales Prediction from existing customer - Logistic Regression


In [59]:
import pandas as pd #useful for loading the dataset
import numpy as np #to perform array

In [60]:
from google.colab import files
uploaded = files.upload()

Saving DigitalAd_dataset_new 1.csv to DigitalAd_dataset_new 1 (1).csv


In [68]:
dataset = pd.read_csv('DigitalAd_dataset_new 1.csv')
print(dataset)

       Min_spent  Clicks   Annual_inc   Age  Purchased   Unnamed: 5  \
0            4.0     21.0     40000.0  41.0           0         NaN   
1            2.0     17.0     40000.0  32.0           0         NaN   
2            7.0     20.0     35000.0  58.0           1         NaN   
3            5.0     15.0     35000.0  54.0           0         NaN   
4            9.0     19.0     10000.0  55.0           1         NaN   
...          ...      ...         ...   ...         ...         ...   
10994       12.0     13.0    100000.0  31.0           0         NaN   
10995       13.0     18.0     76000.0  69.0           1         NaN   
10996        3.0     13.0     40000.0  43.0           1         NaN   
10997        5.0     17.0     58000.0  19.0           0         NaN   
10998       13.0     21.0    100000.0  36.0           1         NaN   

       Unnamed: 6  Unnamed: 7 Unnamed: 8  
0             NaN         NaN        NaN  
1             NaN         NaN        NaN  
2             NaN 

Cleaning data set

In [69]:
dataset = dataset.dropna(subset=['Age', 'Annual_inc','Min_spent','Clicks '], how='any')

In [70]:
print(dataset)

       Min_spent  Clicks   Annual_inc   Age  Purchased   Unnamed: 5  \
0            4.0     21.0     40000.0  41.0           0         NaN   
1            2.0     17.0     40000.0  32.0           0         NaN   
2            7.0     20.0     35000.0  58.0           1         NaN   
3            5.0     15.0     35000.0  54.0           0         NaN   
4            9.0     19.0     10000.0  55.0           1         NaN   
...          ...      ...         ...   ...         ...         ...   
10994       12.0     13.0    100000.0  31.0           0         NaN   
10995       13.0     18.0     76000.0  69.0           1         NaN   
10996        3.0     13.0     40000.0  43.0           1         NaN   
10997        5.0     17.0     58000.0  19.0           0         NaN   
10998       13.0     21.0    100000.0  36.0           1         NaN   

       Unnamed: 6  Unnamed: 7 Unnamed: 8  
0             NaN         NaN        NaN  
1             NaN         NaN        NaN  
2             NaN 

In [71]:
dataset.to_csv('/content/drive/My Drive/cleaned_file.csv',index=False)

In [72]:
dataset = dataset.drop(['Unnamed: 5','Unnamed: 6','Unnamed: 7','Unnamed: 8'], axis=1)

Summerize Data

In [73]:
print(dataset.shape)
print(dataset.head(5))

(9836, 5)
   Min_spent  Clicks   Annual_inc   Age  Purchased 
0        4.0     21.0     40000.0  41.0           0
1        2.0     17.0     40000.0  32.0           0
2        7.0     20.0     35000.0  58.0           1
3        5.0     15.0     35000.0  54.0           0
4        9.0     19.0     10000.0  55.0           1


Segregate Dataset

In [74]:
X = dataset.iloc[:,:-1].values
X

array([[4.0e+00, 2.1e+01, 4.0e+04, 4.1e+01],
       [2.0e+00, 1.7e+01, 4.0e+04, 3.2e+01],
       [7.0e+00, 2.0e+01, 3.5e+04, 5.8e+01],
       ...,
       [3.0e+00, 1.3e+01, 4.0e+04, 4.3e+01],
       [5.0e+00, 1.7e+01, 5.8e+04, 1.9e+01],
       [1.3e+01, 2.1e+01, 1.0e+05, 3.6e+01]])

In [75]:
Y = dataset.iloc[:,-1].values
Y

array([0, 0, 1, ..., 1, 0, 1])

Splitting Dataset into train & test

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.1,random_state=0)

In [80]:
X_train.shape

(8852, 4)

Scaling input

In [81]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print(X_train)
print(X_test)

[[-1.34278128  1.38120787 -1.36395869  0.26707812]
 [-0.59974822 -0.93353126 -0.84147348  0.64510427]
 [-0.35207053  1.61268179 -0.49315001 -0.80399596]
 ...
 [-1.59045897 -1.16500517 -1.36395869  0.77111298]
 [-1.59045897 -0.00763561 -0.84147348 -0.17395238]
 [ 0.39096253 -1.16500517  1.77095255 -0.11094803]]
[[ 1.61264035 -0.91119127 -1.35001345  1.39793001]
 [ 0.87434718  0.01577922 -0.83892803  1.14515046]
 [ 1.1204449   0.24752185  1.7164991  -0.49791663]
 ...
 [ 1.61264035 -0.44770602  1.7164991   0.70278624]
 [-1.09443458 -0.44770602  1.7164991  -1.57222973]
 [-0.60223914 -0.67944865 -0.83892803 -0.49791663]]


Training

In [82]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() #loading the alg.
model.fit(X_train,Y_train) #train


LogisticRegression()

Prediction for all test data

In [83]:
y_pred = model.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score

print('Accuracy of the Model: {0}%'.format(accuracy_score(Y_test,y_pred)*100))

Accuracy of the Model: 48.27235772357724%


Predicting,wheather new customer

In [37]:
age = int(input("Enter New Customer's Age: "))
sal = int(input("Enter New Customer's Salary: "))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer will Buy")

else:
  print("Customer will not Buy")

Enter New Customer's Age: 56
Enter New Customer's Salary: 2000
[1]
Customer will Buy
